Revert "spes: Add configstore HAL entry"
ERROR: files are incompatible: android.hardware.configstore@1.1::ISurfaceFlingerConfigs/default is deprecated in compatibility matrix at FCM Version 5; it should not be served.

This reverts commit 1ecf405.

Change-Id: Ic28310cd027e6b74c4c50a20f6c0cb99fbb5ba8c
Signed-off-by: Kajal4414 <81718060+Kajal4414@users.noreply.github.com>