Partially revert "spes: Declare more missing HALs entries"
ERROR: files are incompatible: android.hardware.bluetooth.a2dp@1.0::IBluetoothAudioOffload/default is deprecated in compatibility matrix at FCM Version 5; it should not be served.

This reverts commit 7e63c52.

Change-Id: Ic47a667be17b4563f3fb09873e565304dcb0eea7
Signed-off-by: Kajal4414 <81718060+Kajal4414@users.noreply.github.com>