spes: Define TARGET_GRALLOC_HANDLE_HAS_RESERVED_SIZE
device/xiaomi/spes/hals/display/gralloc/gr_buf_mgr.cpp:808:34: error: no member named 'reserved_size' in 'private_handle_t'
    buffer->reserved_size = hnd->reserved_size;
                            ~~~  ^
1 error generated.

After this commit f7a21d6.

Change-Id: Iaed6ef6577ad472539c67b5ea01d3416e708b44d
Signed-off-by: Kajal4414 <81718060+Kajal4414@users.noreply.github.com>